### ISSUE TITLE
Add "mq-get-query" function

### ISSUE THREAD

**Issue by niksy** [niksy/salssa#5]
Useful in combination with `scoped-media-query`.

```scss
@function mq-get-query($from: '', $until: '', $and: '', $media-type: 'screen') {
$ret: '#{$media-type}';
@if $from != '' {
$ret: '#{$ret} and (min-width:#{$from})';
}
@if $until != '' {
$ret: '#{$ret} and (max-width:#{$until})'
}
@if $and != '' {
$ret: '#{$ret} and #{$and}'
}
@return $ret;
}

@media #{mq-get-query('','','(orientation:landscape)',all)} {
.foo {
color:red;
}
}
```
